development:
  database: db_dev
  adapter: postgresql
  pool: 10
  timeout: 5000

test:
  database: db_test
  adapter: postgresql
  pool: 10
  timeout: 5000

production:
  database: db_prod
  adapter: postgresql
  pool: 10
  timeout: 5000
